#!/bin/bash
STATIC_INIT_FILE="src/static.c"

function write_static_file()
{
    echo "$STATIC_CONTENT" > $STATIC_INIT_FILE
}

STATIC_CONTENT='/* static.c - autogenerated by makefile */
#include <re_types.h>
#include <re_mod.h>
'

for mod in "$@"; do
    STATIC_CONTENT+="extern const struct mod_export exports_${mod};"
    STATIC_CONTENT+=$'\n'
done
	
STATIC_CONTENT+=$'const struct mod_export *mod_table[] = {\n'
for mod in "$@"; do
    STATIC_CONTENT+=$"    &exports_${mod},"
    STATIC_CONTENT+=$'\n'
done
STATIC_CONTENT+=$'    NULL\n};'

if [ ! -f $STATIC_INIT_FILE ]; then
    write_static_file
else
    EXISTING_CONTENT="$(< "$STATIC_INIT_FILE")"
    # If the contents are the same, then don't re-write it and change the mtime
    if [[ "$EXISTING_CONTENT" != "$STATIC_CONTENT" ]]; then
        write_static_file
    fi
fi
