#!/bin/bash

echo "🎯 Baresip Two-Agent Video Call Test"
echo "======================================"
echo ""
echo "This script sets up two baresip agents for local video testing:"
echo "  Agent 1: SIP:5060, HTTP:8000, Console:5555"
echo "  Agent 2: SIP:5062, HTTP:8002, Console:5557" 
echo ""
echo "To start the test:"
echo ""
echo "1. Terminal 1 - Start Agent 1:"
echo "   cd $(pwd)"
echo "   ./baresip -f /dev/null"
echo ""
echo "2. Terminal 2 - Start Agent 2:"
echo "   cd $(pwd)"
echo "   ./baresip -f /Users/palmarti/.baresip/config-agent2"
echo ""
echo "3. Make a call between agents:"
echo "   In Agent 1: dial sip:agent2@127.0.0.1:5062"
echo "   In Agent 2: accept the incoming call"
echo ""
echo "4. Control via HTTP interfaces:"
echo "   Agent 1: http://localhost:8000"
echo "   Agent 2: http://localhost:8002"
echo ""
echo "5. Console interfaces:"
echo "   Agent 1: nc localhost 5555"  
echo "   Agent 2: nc localhost 5557"
echo ""
echo "Video features to test:"
echo "  - Selfview windows should appear"
echo "  - Video codecs: H.264, H.265, AV1"
echo "  - Take snapshots via HTTP interface"
echo "  - Video filters in action"
echo ""