# Must use GNUInstallDirs to install libraries into correct
# locations on all platforms.
include(GNUInstallDirs)

## Definitions for libre etc.
add_definitions( -DDHAVE_NET_ROUTE_H )
add_definitions( -DDHAVE_SYS_SYSCTL_H )
add_definitions( -DHAVE_DLFCN_H )
add_definitions( -DHAVE_EPOLL )
add_definitions( -DHAVE_FORK )
add_definitions( -DHAVE_GAI_STRERROR )
add_definitions( -DHAVE_GETIFADDRS )
add_definitions( -DHAVE_GETOPT )
add_definitions( -DHAVE_INET_NTOP )
add_definitions( -DHAVE_INET_PTON )
add_definitions( -DHAVE_INET6 )
add_definitions( -DHAVE_INTTYPES_H )
add_definitions( -DHAVE_PTHREAD )
add_definitions( -DHAVE_PWD_H )
add_definitions( -DHAVE_RESOLV )
add_definitions( -DHAVE_ROUTE_LIST )
add_definitions( -DHAVE_SETRLIMIT )
add_definitions( -DHAVE_SIGNAL )
add_definitions( -DHAVE_STDBOOL_H )
add_definitions( -DHAVE_STRERROR_R )
add_definitions( -DHAVE_STRINGS_H )
add_definitions( -DHAVE_SYS_TIME_H )
add_definitions( -DHAVE_SYSLOG )
add_definitions( -DHAVE_UNAME )
add_definitions( -DHAVE_UNISTD_H )
add_definitions( -DUSE_DTLS )
add_definitions( -DUSE_DTLS_SRTP )
add_definitions( -DUSE_OPENSSL )
add_definitions( -DUSE_OPENSSL_DTLS )
add_definitions( -DUSE_OPENSSL_SRTP )
add_definitions( -DUSE_TLS )
add_definitions( -DJBUF_STAT )

if(STATIC)
    add_definitions( -DSTATIC )
endif()
